2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_setup.py:_flush():76] Configure stats pid to 28548
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_setup.py:_flush():76] Loading settings from /home/zyk/.config/wandb/settings
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_setup.py:_flush():76] Loading settings from /home/zyk/Personal_study_projects/ECG_mit-bih/wandb/settings
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/zyk/Personal_study_projects/ECG_mit-bih/main.py', 'program': '/home/zyk/Personal_study_projects/ECG_mit-bih/main.py'}
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_init.py:_log_setup():526] Logging user logs to /home/zyk/Personal_study_projects/ECG_mit-bih/wandb/run-20240117_122405-juo7twt3/logs/debug.log
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_init.py:_log_setup():527] Logging internal logs to /home/zyk/Personal_study_projects/ECG_mit-bih/wandb/run-20240117_122405-juo7twt3/logs/debug-internal.log
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_init.py:init():566] calling init triggers
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_init.py:init():616] starting backend
2024-01-17 12:24:05,030 INFO    MainThread:28548 [wandb_init.py:init():620] setting up manager
2024-01-17 12:24:05,032 INFO    MainThread:28548 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-17 12:24:05,033 INFO    MainThread:28548 [wandb_init.py:init():628] backend started and connected
2024-01-17 12:24:05,037 INFO    MainThread:28548 [wandb_init.py:init():720] updated telemetry
2024-01-17 12:24:05,043 INFO    MainThread:28548 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-01-17 12:24:06,363 ERROR   MainThread:28548 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-01-17 12:24:07,430 ERROR   MainThread:28548 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/zyk/anaconda3/envs/ecg/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/zyk/anaconda3/envs/ecg/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-01-17 12:24:09,441 WARNING MsgRouterThr:28548 [router.py:message_loop():77] message_loop has been closed
